// AUTO-GENERATED by scripts/generate-starter-decks.mjs
import type { DeckList } from "@/lib/game/types";

export const STARTER_DECKS: DeckList[] = [
  {
    "id": "starter-fury",
    "name": "Fury Strike (Starter)",
    "legendId": "69bc5bd7d308c64675ca87fa",
    "chosenChampionId": "69bc5bcfd308c64675ca8763",
    "mainDeck": [
      {
        "defId": "69bc5bcfd308c64675ca8763",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8813",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8812",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8814",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8815",
        "quantity": 3
      },
      {
        "defId": "69c43cd3c2f7428c5d24b4f1",
        "quantity": 3
      },
      {
        "defId": "69bc5be9d308c64675ca895b",
        "quantity": 3
      },
      {
        "defId": "69bc5becd308c64675ca8993",
        "quantity": 3
      },
      {
        "defId": "69bc5bead308c64675ca8962",
        "quantity": 3
      },
      {
        "defId": "69bc5befd308c64675ca89c5",
        "quantity": 3
      },
      {
        "defId": "69bc5beed308c64675ca89b8",
        "quantity": 3
      },
      {
        "defId": "69bc5beed308c64675ca89b5",
        "quantity": 3
      },
      {
        "defId": "69bc5bdfd308c64675ca8891",
        "quantity": 3
      },
      {
        "defId": "69bc5bdfd308c64675ca888b",
        "quantity": 1
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bc6d308c64675ca86bc",
        "quantity": 7
      },
      {
        "defId": "69bc5bcdd308c64675ca8740",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  },
  {
    "id": "starter-mind",
    "name": "Mind & Calm (Starter)",
    "legendId": "69bc5bebd308c64675ca8981",
    "chosenChampionId": "69bc5bedd308c64675ca899b",
    "mainDeck": [
      {
        "defId": "69bc5bedd308c64675ca899b",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8813",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8812",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8814",
        "quantity": 3
      },
      {
        "defId": "69bc5bd8d308c64675ca8815",
        "quantity": 3
      },
      {
        "defId": "69bc5be9d308c64675ca8953",
        "quantity": 3
      },
      {
        "defId": "69bc5beed308c64675ca89b7",
        "quantity": 3
      },
      {
        "defId": "69bc5beed308c64675ca89b6",
        "quantity": 3
      },
      {
        "defId": "69bc5bedd308c64675ca8999",
        "quantity": 3
      },
      {
        "defId": "69bc5be2d308c64675ca88d2",
        "quantity": 3
      },
      {
        "defId": "69bc5be2d308c64675ca88d1",
        "quantity": 3
      },
      {
        "defId": "69bc5be8d308c64675ca8949",
        "quantity": 3
      },
      {
        "defId": "69bc5be6d308c64675ca8922",
        "quantity": 3
      },
      {
        "defId": "69c43cd2c2f7428c5d24b4e2",
        "quantity": 1
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bcbd308c64675ca8718",
        "quantity": 7
      },
      {
        "defId": "69bc5bc9d308c64675ca86e4",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  }
];
