// AUTO-GENERATED by scripts/build-precon-decks.mjs
// Source: Origins Proving Grounds preconstructed decks (Riot, 2025)
import type { DeckList } from "@/lib/game/types";

export const STARTER_DECKS: DeckList[] = [
  {
    "id": "pg-annie",
    "name": "Annie — Dark Child (Proving Grounds)",
    "legendId": "69bc5bd9d308c64675ca8826",
    "chosenChampionId": "69bc5bd8d308c64675ca8816",
    "mainDeck": [
      {
        "defId": "69bc5bd8d308c64675ca8816",
        "quantity": 3
      },
      {
        "defId": "69bc5bd9d308c64675ca8827",
        "quantity": 2
      },
      {
        "defId": "69bc5bd8d308c64675ca8817",
        "quantity": 2
      },
      {
        "defId": "69bc5bd8d308c64675ca8818",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca881f",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8820",
        "quantity": 2
      },
      {
        "defId": "69bc5bd2d308c64675ca8797",
        "quantity": 3
      },
      {
        "defId": "69bc5bc8d308c64675ca86e1",
        "quantity": 3
      },
      {
        "defId": "69bc5bd0d308c64675ca877b",
        "quantity": 3
      },
      {
        "defId": "69bc5bd0d308c64675ca8771",
        "quantity": 3
      },
      {
        "defId": "69bc5bd0d308c64675ca877f",
        "quantity": 3
      },
      {
        "defId": "69bc5bc7d308c64675ca86bf",
        "quantity": 3
      },
      {
        "defId": "69bc5bc6d308c64675ca86b9",
        "quantity": 3
      },
      {
        "defId": "69bc5bd0d308c64675ca8775",
        "quantity": 3
      },
      {
        "defId": "69bc5bd0d308c64675ca877d",
        "quantity": 3
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bc6d308c64675ca86bc",
        "quantity": 7
      },
      {
        "defId": "69bc5bd0d308c64675ca876d",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  },
  {
    "id": "pg-garen",
    "name": "Garen — Might of Demacia (Proving Grounds)",
    "legendId": "69bc5bd9d308c64675ca882c",
    "chosenChampionId": "69bc5bd9d308c64675ca881c",
    "mainDeck": [
      {
        "defId": "69bc5bd9d308c64675ca881c",
        "quantity": 3
      },
      {
        "defId": "69bc5bd9d308c64675ca882d",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8825",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8824",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca881d",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca881e",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8821",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8822",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8823",
        "quantity": 2
      },
      {
        "defId": "69bc5bd4d308c64675ca87c5",
        "quantity": 3
      },
      {
        "defId": "69bc5bcfd308c64675ca8769",
        "quantity": 3
      },
      {
        "defId": "69bc5bd5d308c64675ca87df",
        "quantity": 3
      },
      {
        "defId": "69bc5bcfd308c64675ca8760",
        "quantity": 3
      },
      {
        "defId": "69bc5bced308c64675ca8748",
        "quantity": 3
      },
      {
        "defId": "69bc5bced308c64675ca8754",
        "quantity": 3
      },
      {
        "defId": "69bc5bd3d308c64675ca87b0",
        "quantity": 3
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bcdd308c64675ca8740",
        "quantity": 7
      },
      {
        "defId": "69bc5bd2d308c64675ca87a2",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  },
  {
    "id": "pg-lux",
    "name": "Lux — Lady of Luminosity (Proving Grounds)",
    "legendId": "69bc5bd9d308c64675ca882a",
    "chosenChampionId": "69bc5bd8d308c64675ca881b",
    "mainDeck": [
      {
        "defId": "69bc5bd8d308c64675ca881b",
        "quantity": 3
      },
      {
        "defId": "69bc5bd9d308c64675ca882b",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8825",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8824",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8821",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8822",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca8823",
        "quantity": 2
      },
      {
        "defId": "69bc5bd4d308c64675ca87c5",
        "quantity": 3
      },
      {
        "defId": "69bc5bcdd308c64675ca8739",
        "quantity": 3
      },
      {
        "defId": "69bc5bd3d308c64675ca87b0",
        "quantity": 3
      },
      {
        "defId": "69bc5bccd308c64675ca8728",
        "quantity": 3
      },
      {
        "defId": "69bc5bccd308c64675ca871f",
        "quantity": 3
      },
      {
        "defId": "69bc5bcbd308c64675ca871a",
        "quantity": 3
      },
      {
        "defId": "69bc5bd5d308c64675ca87db",
        "quantity": 3
      },
      {
        "defId": "69bc5bd3d308c64675ca87ad",
        "quantity": 3
      },
      {
        "defId": "69bc5bd3d308c64675ca87a9",
        "quantity": 1
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bcbd308c64675ca8718",
        "quantity": 7
      },
      {
        "defId": "69bc5bd2d308c64675ca87a2",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  },
  {
    "id": "pg-master-yi",
    "name": "Master Yi — Wuju Bladesman (Proving Grounds)",
    "legendId": "69bc5bd9d308c64675ca8828",
    "chosenChampionId": "69bc5bd8d308c64675ca8819",
    "mainDeck": [
      {
        "defId": "69bc5bd8d308c64675ca8819",
        "quantity": 3
      },
      {
        "defId": "69bc5bd9d308c64675ca8829",
        "quantity": 2
      },
      {
        "defId": "69bc5bd8d308c64675ca881a",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca881c",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca881d",
        "quantity": 2
      },
      {
        "defId": "69bc5bd9d308c64675ca881e",
        "quantity": 2
      },
      {
        "defId": "69bc5bcfd308c64675ca8769",
        "quantity": 3
      },
      {
        "defId": "69bc5bcbd308c64675ca8710",
        "quantity": 3
      },
      {
        "defId": "69bc5bcfd308c64675ca8760",
        "quantity": 3
      },
      {
        "defId": "69bc5bced308c64675ca8748",
        "quantity": 3
      },
      {
        "defId": "69bc5bced308c64675ca8754",
        "quantity": 3
      },
      {
        "defId": "69bc5bc9d308c64675ca86e6",
        "quantity": 3
      },
      {
        "defId": "69bc5bc9d308c64675ca86e8",
        "quantity": 3
      },
      {
        "defId": "69bc5bc9d308c64675ca86e9",
        "quantity": 3
      },
      {
        "defId": "69bc5bcdd308c64675ca8743",
        "quantity": 3
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bc9d308c64675ca86e4",
        "quantity": 7
      },
      {
        "defId": "69bc5bcdd308c64675ca8740",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  }
];
