// AUTO-GENERATED by scripts/generate-starter-decks.mjs
import type { DeckList } from "@/lib/game/types";

export const STARTER_DECKS: DeckList[] = [
  {
    "id": "starter-volibear",
    "name": "Volibear — Relentless Storm",
    "legendId": "69bc5bd4d308c64675ca87ca",
    "chosenChampionId": "69bc5bcfd308c64675ca8762",
    "mainDeck": [
      {
        "defId": "69bc5bcfd308c64675ca8762",
        "quantity": 3
      },
      {
        "defId": "69bc5bcfd308c64675ca8769",
        "quantity": 3
      },
      {
        "defId": "69bc5bc8d308c64675ca86e1",
        "quantity": 3
      },
      {
        "defId": "69bc5be4d308c64675ca88f7",
        "quantity": 3
      },
      {
        "defId": "69bc5be4d308c64675ca88f2",
        "quantity": 3
      },
      {
        "defId": "69bc5be4d308c64675ca88f0",
        "quantity": 3
      },
      {
        "defId": "69bc5be2d308c64675ca88cc",
        "quantity": 3
      },
      {
        "defId": "69c43cd3c2f7428c5d24b4f1",
        "quantity": 3
      },
      {
        "defId": "69c8378d2c3db56eb7d760cb",
        "quantity": 3
      },
      {
        "defId": "69c5be69bf82ff7cb69f428a",
        "quantity": 3
      },
      {
        "defId": "69c5be6abf82ff7cb69f4294",
        "quantity": 3
      },
      {
        "defId": "69bc5bf3d308c64675ca8a0d",
        "quantity": 3
      },
      {
        "defId": "69bff35758d0fbca04e9372f",
        "quantity": 3
      },
      {
        "defId": "69bc5bcfd308c64675ca8760",
        "quantity": 1
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bc6d308c64675ca86bc",
        "quantity": 7
      },
      {
        "defId": "69bc5bcdd308c64675ca8740",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  },
  {
    "id": "starter-lillia",
    "name": "Lillia — Bashful Bloom",
    "legendId": "69bc5be9d308c64675ca894e",
    "chosenChampionId": "69bc5bedd308c64675ca8998",
    "mainDeck": [
      {
        "defId": "69bc5bedd308c64675ca8998",
        "quantity": 3
      },
      {
        "defId": "69bc5bcdd308c64675ca8739",
        "quantity": 3
      },
      {
        "defId": "69bc5bcbd308c64675ca8710",
        "quantity": 3
      },
      {
        "defId": "69bc5be0d308c64675ca88a5",
        "quantity": 3
      },
      {
        "defId": "69bc5be0d308c64675ca88a7",
        "quantity": 3
      },
      {
        "defId": "69bc5bdad308c64675ca8835",
        "quantity": 3
      },
      {
        "defId": "69bc5be6d308c64675ca891a",
        "quantity": 3
      },
      {
        "defId": "69bc5be6d308c64675ca8921",
        "quantity": 3
      },
      {
        "defId": "69bc5bf3d308c64675ca8a15",
        "quantity": 3
      },
      {
        "defId": "69bc5bf3d308c64675ca8a11",
        "quantity": 3
      },
      {
        "defId": "69bff35658d0fbca04e9372c",
        "quantity": 3
      },
      {
        "defId": "69bff35658d0fbca04e9371e",
        "quantity": 3
      },
      {
        "defId": "69bd162140ff39fe1396df8a",
        "quantity": 3
      },
      {
        "defId": "69bc5bc9d308c64675ca86e6",
        "quantity": 1
      }
    ],
    "runeDeck": [
      {
        "defId": "69bc5bc9d308c64675ca86e4",
        "quantity": 7
      },
      {
        "defId": "69bc5bcbd308c64675ca8718",
        "quantity": 5
      }
    ],
    "battlefieldIds": [
      "69bc5befd308c64675ca89c0",
      "69bc5befd308c64675ca89bf",
      "69bc5befd308c64675ca89be"
    ]
  }
];
